name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Transfer files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: radica.dev
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: dist
        target: /tmp/

    - name: Move files to nginx root
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: radica.dev
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          rm -rf ${{ secrets.SITE_DIR }}/html
          mv /tmp/dist /tmp/html
          mv /tmp/html ${{ secrets.SITE_DIR }}/
