name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: radica.dev
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          rm -rf /var/www/radica.dev/html/*
          mkdir -p /var/www/radica.dev/html
          tar -xzf site.tar.gz -C /var/www/radica.dev/html
    - name: Package build files
      run: tar -czf site.tar.gz -C dist .

